"""Criação inicial da tabela de peças

Revision ID: cbbce3dd4673
Revises: 4e8b20fe2808
Create Date: 2025-09-29 18:27:08.423286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbbce3dd4673'
down_revision = '4e8b20fe2808'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.String(length=50), nullable=False),
    sa.Column('seller', sa.String(length=100), nullable=True),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('product_id', sa.String(length=100), nullable=False),
    sa.Column('car_model', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parts')
    # ### end Alembic commands ###
